fix: skip unsafe methods
fastify/csrf-protection pull request #167
Opened 2024-10-12 21:29 UTC by johaven

#### Checklist

- [x] run `npm run test`
- [x] tests and/or benchmarks are included
- [x] documentation is changed or added
- [x] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

Fix issue: https://github.com/fastify/csrf-protection/issues/166

This PR introduce the ability to pass the protected methods as module options

2024-10-12 21:42 UTC, Uzlopak requested changes
I dislike this approach. You basically add the check that the method is in the array on every request. But this is not necessary to be done on every request. You could hook onRoute and if the route is an unprotected route you add csrfProtection as preParsing hook to the routeObject of the onRoute hook.

2024-10-12 21:56 UTC, johaven commented
@Uzlopak I'm not very familiar with the 'onRoute' hook yet (and I hadn't thought about it :p)

Is the hook triggered after plugins registration ?

2024-10-12 22:38 UTC, Uzlopak commented
It would be a large text to describe what i mean. 

See following code pieces:
https://github.com/fastify/fastify-response-validation/blob/daecd7ce0b352e002da5a05d0dbd33acd85fa4d8/index.js#L35

1. add a new option like `autoProtect` for the plugin level and `csrfProtect` on the route level  (shitty name but just to demonstrate) which can be set to true and `hook` option, which can be a lifecycle hook like `onRequest` or `preParse`.
2. about in line [63](https://github.com/fastify/csrf-protection/blob/680c1fce1d67e987acdbd22413fe2970562ce8dc/index.js#L63)  add following code
```js
  if (opts.autoProtect === true) {
    fastify.addHook('onRoute', onRoute)
  }
```

Now we need the onRoute Code which we for simplicity put into the plugin function to access the pluginOPtions opts

```js
  function onRoute (routeOpts) {
    const { hook } = opts // <-- pluginOptions
    if (routeOpts.csrfProtect || (opts.autoProtect && opts.protectedMethods.includes(routeOpts.method)) {
      routeOpts[hook] = routeOpts[hook] || []
      routeOpts[hook].push(csrfProtection)
    }
  }

```

If you know your csrf token is in body, you need to parse it, so you would set the hook to `preValidation` but if you know the token is in the header, you can already process the request in the onRequest stage, as the headers should be there already.

And of course validate if hook is a valid lifecycle hook and keep into account that onRequest and preValidation have the arity of 3 but preParsing has the arity of 4. So you could do it like [here](https://github.com/fastify/fastify-cookie/pull/204/files)  

This should help you to get atleast a mvp. there are probably some improvements possible to improve the DX.

2025-01-12 10:39 UTC, Fdawgs requested changes
I don't think this is a good idea as @Uzlopak suggested. This could probably be a line in the readme stating that you don't need this for safe methods, and to use route encapsulation so it doesn't apply to safe methods on routes.

2025-01-12 11:50 UTC, johaven commented
You can close this PR, i don't use this module on my side, it was just to help but right now I don't have a lot of time :)

2025-01-21 08:58 UTC, closed without merging